// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMaster.API.Data;

#nullable disable

namespace StockMaster.API.Migrations
{
    [DbContext(typeof(StockMasterDbContext))]
    partial class StockMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMaster.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 406, DateTimeKind.Local).AddTicks(7175),
                            Description = "Productos electrónicos",
                            Icon = "fa-laptop",
                            IsActive = true,
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Color = "purple",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 408, DateTimeKind.Local).AddTicks(6055),
                            Description = "Vestimenta y accesorios",
                            Icon = "fa-tshirt",
                            IsActive = true,
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 408, DateTimeKind.Local).AddTicks(6069),
                            Description = "Productos alimenticios",
                            Icon = "fa-apple-alt",
                            IsActive = true,
                            Name = "Alimentos"
                        },
                        new
                        {
                            Id = 4,
                            Color = "orange",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 408, DateTimeKind.Local).AddTicks(6071),
                            Description = "Herramientas y equipos",
                            Icon = "fa-tools",
                            IsActive = true,
                            Name = "Herramientas"
                        },
                        new
                        {
                            Id = 5,
                            Color = "red",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 408, DateTimeKind.Local).AddTicks(6072),
                            Description = "Artículos deportivos",
                            Icon = "fa-futbol",
                            IsActive = true,
                            Name = "Deportes"
                        },
                        new
                        {
                            Id = 6,
                            Color = "cyan",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 408, DateTimeKind.Local).AddTicks(6073),
                            Description = "Libros y útiles escolares",
                            Icon = "fa-book",
                            IsActive = true,
                            Name = "Librería"
                        });
                });

            modelBuilder.Entity("StockMaster.API.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("StockMaster.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(3120),
                            Description = "Laptop de alta gama",
                            IsActive = true,
                            MinStock = 5,
                            Name = "Laptop Dell XPS 13",
                            Price = 1200.00m,
                            SKU = "PROD-001",
                            Stock = 15,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(4252),
                            Description = "Mouse inalámbrico premium",
                            IsActive = true,
                            MinStock = 10,
                            Name = "Mouse Logitech MX Master",
                            Price = 89.99m,
                            SKU = "PROD-002",
                            Stock = 45,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(4258),
                            Description = "Teclado gaming",
                            IsActive = true,
                            MinStock = 10,
                            Name = "Teclado Mecánico RGB",
                            Price = 149.99m,
                            SKU = "PROD-003",
                            Stock = 30,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(4260),
                            Description = "Camiseta de algodón",
                            IsActive = true,
                            MinStock = 30,
                            Name = "Camiseta Deportiva",
                            Price = 29.99m,
                            SKU = "PROD-004",
                            Stock = 120,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(4262),
                            Description = "Jean clásico",
                            IsActive = true,
                            MinStock = 20,
                            Name = "Pantalón Jean",
                            Price = 59.99m,
                            SKU = "PROD-005",
                            Stock = 80,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("StockMaster.API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Corrientes 1234",
                            City = "Buenos Aires",
                            ContactName = "Juan Pérez",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(1522),
                            Email = "ventas@techsupplies.com",
                            IsActive = true,
                            Name = "Tech Supplies SA",
                            Phone = "+54 11 4567-8900"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle San Martín 567",
                            City = "Córdoba",
                            ContactName = "María González",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(2431),
                            Email = "info@distcentral.com",
                            IsActive = true,
                            Name = "Distribuidora Central",
                            Phone = "+54 11 5432-1098"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av. San Martín 890",
                            City = "Mendoza",
                            ContactName = "Carlos Rodríguez",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(2434),
                            Email = "compras@impandina.com",
                            IsActive = true,
                            Name = "Importadora Andina",
                            Phone = "+54 261 423-9876"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bv. Oroño 234",
                            City = "Rosario",
                            ContactName = "Ana Martínez",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 1, 16, 16, 36, 32, 409, DateTimeKind.Local).AddTicks(2436),
                            Email = "contacto@almalog.com",
                            IsActive = false,
                            Name = "Almacén Logístico",
                            Phone = "+54 341 456-7890"
                        });
                });

            modelBuilder.Entity("StockMaster.API.Models.Movement", b =>
                {
                    b.HasOne("StockMaster.API.Models.Product", "Product")
                        .WithMany("Movements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockMaster.API.Models.Product", b =>
                {
                    b.HasOne("StockMaster.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockMaster.API.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StockMaster.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StockMaster.API.Models.Product", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("StockMaster.API.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
